services:
  bot:
    container_name: telegram-bot-dev
    build: ./bot
    restart: unless-stopped
    env_file:
      - .env.dev
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - internal-dev
    volumes:
      - ./bot/src:/app/src  # Монтируем исходники для hot-reload

  postgres:
    container_name: telegram-postgres-dev
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: telegram_bot_db_dev
      POSTGRES_USER: bot_user_dev
      POSTGRES_PASSWORD: DevPass2024!
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data
    networks:
      - internal-dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bot_user_dev -d telegram_bot_db_dev"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-dev-data:

networks:
  internal-dev:
    driver: bridge
