#!/bin/bash
echo "=== Мониторинг сервера ==="
echo "Дата: $(date)"
echo ""
echo "--- Docker контейнеры ---"
docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"
echo ""
echo "--- Использование ресурсов ---"
docker stats --no-stream --format "table {{.Name}}\t{{.CPUPerc}}\t{{.MemUsage}}\t{{.NetIO}}"
echo ""
echo "--- Дисковое пространство ---"
df -h / /opt
echo ""
echo "--- Размер базы данных ---"
docker exec telegram-postgres psql -U bot_user -d telegram_bot_db -c "SELECT pg_size_pretty(pg_database_size('telegram_bot_db'));"
echo ""
echo "--- Количество пользователей ---"
docker exec telegram-postgres psql -U bot_user -d telegram_bot_db -c "SELECT COUNT(*) as total_users FROM users;"
echo ""
echo "--- Последние рассылки ---"
docker exec telegram-postgres psql -U bot_user -d telegram_bot_db -c "SELECT id, status, total_users, sent_count, failed_count, created_at FROM mailings ORDER BY id DESC LIMIT 5;"
